#!/bin/bash
# Quick Start Guide for Portfolio Website

echo "================================================"
echo "CMU 15-113 Portfolio Website - Quick Start"
echo "================================================"
echo ""
echo "✅ Your portfolio website is ready!"
echo ""
echo "STEP 1: Add Images"
echo "--------"
echo "Place 12 images in the 'assets/' folder:"
echo "  - profile.jpg (your photo)"
echo "  - project-portfolio.png"
echo "  - project-ai-ads.png"
echo "  - project-edtech-ar.png"
echo "  - seal-01.jpg, seal-02.jpg, seal-03.jpg, seal-04.jpg"
echo "  - cetacean-talk-01.jpg, cetacean-talk-02.jpg"
echo "  - ocean-speech-01.jpg, ocean-speech-02.jpg"
echo ""
echo "STEP 2: Test Locally (Optional)"
echo "--------"
echo "Start a local server to test before deployment:"
echo ""
echo "  Option A - Python 3:"
echo "    python -m http.server 8000"
echo ""
echo "  Option B - Python 2:"
echo "    python -m SimpleHTTPServer 8000"
echo ""
echo "  Option C - Node.js (http-server):"
echo "    npm install -g http-server"
echo "    http-server"
echo ""
echo "Then open: http://localhost:8000"
echo ""
echo "STEP 3: Deploy to GitHub Pages"
echo "--------"
echo "$ git add ."
echo "$ git commit -m 'Add portfolio website'"
echo "$ git push origin main"
echo ""
echo "Then in your GitHub repo:"
echo "  1. Go to Settings > Pages"
echo "  2. Select 'Deploy from a branch'"
echo "  3. Choose branch: main"
echo "  4. Click Save"
echo ""
echo "Your site will be live at:"
echo "https://YOUR-USERNAME.github.io/REPO-NAME/"
echo ""
echo "================================================"
echo "TESTING CHECKLIST"
echo "================================================"
echo ""
echo "[ ] Images load in all sections"
echo "[ ] Hamburger menu works on mobile (<768px)"
echo "[ ] Lightbox opens when clicking seal images"
echo "[ ] ESC key closes lightbox"
echo "[ ] All links work (email, LinkedIn, Instagram)"
echo "[ ] No horizontal scrolling on mobile"
echo "[ ] Tab navigation works throughout site"
echo "[ ] Focus outline visible on all buttons/links"
echo "[ ] Responsive on desktop, tablet, and mobile"
echo ""
echo "================================================"
echo "FILES IN YOUR PROJECT"
echo "================================================"
echo ""
ls -lh *.html *.css *.js *.md *.txt 2>/dev/null | awk '{print $9, "(" $5 ")"}'
echo ""
echo "assets/ directory:"
ls -lh assets/ 2>/dev/null || echo "  (empty - add images here)"
echo ""
echo "================================================"
echo "DOCUMENTATION"
echo "================================================"
echo ""
echo "- README.md              → Full project documentation"
echo "- CODE_OVERVIEW.md       → Code structure & customization"
echo "- PROJECT_SUMMARY.txt    → Feature checklist & deployment"
echo "- SUBMISSION_CHECKLIST.md → Final verification before submit"
echo ""
echo "================================================"
echo "SUPPORT"
echo "================================================"
echo ""
echo "For questions, see:"
echo "- README.md (Troubleshooting section)"
echo "- CODE_OVERVIEW.md (Code structure)"
echo "- GitHub Pages docs: https://pages.github.com"
echo ""
echo "================================================"
echo "Ready to launch? 🚀"
echo "================================================"
